[package]
name = "minion"
version = "0.1.0"
authors = ["Mikail Bagishov <bagishov.mikail@yandex.ru>"]
edition = "2018"

[dependencies]
libc = "0.2.82"
errno = "0.2.7"
rand = "0.8.2"
serde = { version = "1.0.121", features = ["derive"] }
serde_json = "1.0.61"
tiny-nix-ipc = { git = "https://github.com/myfreeweb/tiny-nix-ipc", features = ["ser_json", "zero_copy"] }
nix = "0.19.1"
backtrace = "0.3.56"
thiserror = "1.0.23"
anyhow = "1.0.38"
once_cell = "1.5.2"
futures-util = "0.3.12"
tokio = { version = "1.1.0", features = ["net"] }
tracing = "0.1.22"
itoa = "0.4.7"
serde = { version = "1.0.106", features = ["derive"] }
thiserror = "1.0.19"
anyhow = "1.0.32"
futures-util = "0.3.6"
once_cell = "1.4.1"
backtrace = "0.3.46"

[target.'cfg(target_os="linux")'.dependencies]
tiny-nix-ipc = { git = "https://github.com/myfreeweb/tiny-nix-ipc", features = ["ser_json", "zero_copy"] }
procfs = "0.7.8"
nix = {git = "https://github.com/nix-rust/nix"}
libc = "0.2.68"
errno = "0.2.5"
serde_json = "1.0.51"
tokio = { version = "0.3.2", features = ["net"] }

[target.'cfg(target_os="windows")'.dependencies]
winapi = { version = "0.3.9", features = ["std", "processthreadsapi", "jobapi2", "errhandlingapi",
 "namedpipeapi", "fileapi", "synchapi", "winnt", "userenv", "handleapi", "securitybaseapi", "sddl"] }

[workspace]
members = ["minion-ffi", ".", "minion-tests", "minion-cli"]
