[package]
name = "minion"
version = "0.1.0"
authors = ["Mikail Bagishov <bagishov.mikail@yandex.ru>"]
edition = "2018"

[dependencies]
libc= "0.2.68"
errno= "0.2.5"
rand = "0.7.3"
cfg-if = "0.1.10"
serde = { version = "1.0.106", features = ["derive"] }
serde_json = "1.0.51"
tiny-nix-ipc = { git = "https://github.com/myfreeweb/tiny-nix-ipc", features = ["ser_json", "zero_copy"] }
procfs = "0.7.8"
nix = {git = "https://github.com/nix-rust/nix"}
snafu = "0.6.6"
backtrace = "0.3.46"
thiserror = "1.0.15"

