[package]
name = "minion"
version = "0.1.0"
authors = ["Mikail Bagishov <bagishov.mikail@yandex.ru>"]
edition = "2018"

[dependencies]
libc = "0.2.86"
errno = "0.2.7"
rand = "0.8.3"
serde = { version = "1.0.123", features = ["derive"] }
serde_json = "1.0.62"
backtrace = "0.3.56"
thiserror = "1.0.23"
anyhow = "1.0.38"
once_cell = "1.5.2"
futures-util = "0.3.12"
tokio = { version = "1.2.0", features = ["net"] }
tracing = "0.1.23"
itoa = "0.4.7"

[target.'cfg(target_os="linux")'.dependencies]
tiny-nix-ipc = { git = "https://github.com/myfreeweb/tiny-nix-ipc", features = ["ser_json", "zero_copy"] }
nix = {git = "https://github.com/nix-rust/nix"}
libc = "0.2.86"
errno = "0.2.7"
serde_json = "1.0.62"
tokio = { version = "1.2.0", features = ["net"] }

[target.'cfg(target_os="windows")'.dependencies]
winapi = { version = "0.3.9", features = ["std", "processthreadsapi", "jobapi2", "errhandlingapi",
 "namedpipeapi", "fileapi", "synchapi", "winnt", "userenv", "handleapi", "securitybaseapi", "sddl"] }

[workspace]
members = ["minion-ffi", ".", "minion-tests", "minion-cli"]
