[package]
name = "minion"
version = "0.1.0"
authors = ["Mikail Bagishov <bagishov.mikail@yandex.ru>"]
edition = "2018"

[dependencies]
libc = "0.2.68"
errno = "0.2.5"
rand = "0.7.3"
serde = { version = "1.0.106", features = ["derive"] }
serde_json = "1.0.51"
tiny-nix-ipc = { git = "https://github.com/myfreeweb/tiny-nix-ipc", features = ["ser_json", "zero_copy"] }
procfs = "0.7.8"
nix = { version = "0.19.0" }
backtrace = "0.3.46"
thiserror = "1.0.19"
anyhow = "1.0.32"
once_cell = "1.4.1"
futures-util = "0.3.6"
tokio = { version = "0.3.2", features = ["net"] }

[workspace]
members = ["minion-ffi", ".", "minion-tests", "minion-cli"]
