[package]
name = "minion-tests"
version = "0.1.0"
authors = ["Mikail Bagishov <bagishov.mikail@yandex.ru>"]
edition = "2018"

[dependencies]
once_cell = "1.5.2"
minion = {path = ".."}
clap = "2.33.3"
tempfile = "3.2.0"
tokio = { version = "1.1.0", features = ["macros", "rt"] }
tracing-subscriber = "0.2.15"

[target.'cfg(target_os="linux")'.dependencies]
nix = "0.17.0"

[target.'cfg(target_os="windows")'.dependencies]
winapi = { version = "0.3.9", features = ["processthreadsapi"] }
