[package]
name = "minion-tests"
version = "0.1.0"
authors = ["Mikail Bagishov <bagishov.mikail@yandex.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.4.0"
minion = {path = ".."}
clap = "2.33.1"
nix = "0.17.0"
tempfile = "3.1.0"
