name: Rust

on:
  push:
    branches: 
      - master
  pull_request:

env:
  CARGO_TERM_COLOR: always
jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          components: rustfmt
      - name: Check formatting
        run: | 
          rm -rf .cargo
          cargo fmt --all -- --check
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: nightly
          components: clippy
          override: true
      - name: Run clippy
        run: |
          cargo clippy --workspace -- -Dclippy::all -Dwarnings
  check-platform-support:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
      - name: Remove cargo config
        run: rm -rf .cargo
      - name: Check musl
        run: |
          rustup target add x86_64-unknown-linux-musl
          cargo check -p minion -p minion-ffi -p minion-cli --target x86_64-unknown-linux-musl
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1.0.6
        with: 
          toolchain: nightly
          override: true
      - name: Compile tests
        run: |
          rm -rf .cargo
          cd minion-tests 
          TARGET=x86_64-unknown-linux-musl
          rustup target add $TARGET
          cargo build -Zunstable-options --out-dir=../out --target=$TARGET
      - name: Run tests
        run: |
          sudo ./out/minion-tests --trace
        timeout-minutes: 3 
      - name: Collect logs
        if: always()
        run: |
          mkdir /tmp/logs
          cp ./strace* /tmp/logs
      - uses: actions/upload-artifact@v1
        if: always()
        with:
          path: /tmp/logs
          name: tests-trace
  nightly-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: nightly
          override: true
      - name: Run special lints
        run: |
          rm -rf .cargo
          cargo check --workspace
        env:
          RUSTFLAGS: -Wunused-crate-dependencies --cfg minion_nightly
      
