name: Rust

on:
  push:
    branches: 
      - master
  pull_request:

env:
  CARGO_TERM_COLOR: always
jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          components: rustfmt
      - name: Check formatting
        run: | 
          rm -rf .cargo
          cargo fmt --all -- --check
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          components: clippy
      - name: Run clippy
        run: |
          rm -rf .cargo
          cargo clippy --workspace -- -Dclippy::all
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1.0.6
        with: 
          toolchain: stable
      - name: Compile tests
        run: |
          rm -rf .cargo
          mkdir build
          cd build
          cmake ../minion-ffi/tests
          cmake --build .
      - name: Run tests
        run: |
          cd build
          
          # TODO
          # sudo ./mft
  nightly-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: nightly
          override: true
      - name: Run special lints
        run: |
          rm -rf .cargo
          cargo check --workspace
        env:
          RUSTFLAGS: -Wunused-crate-dependencies --cfg minion_nightly
      
